// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameForbiddenLink = "keepshare_forbidden_link"

// ForbiddenLink mapped from table <keepshare_forbidden_link>
type ForbiddenLink struct {
	ChannelID        string    `gorm:"column:channel_id;primaryKey" json:"channel_id"`
	OriginalLinkHash string    `gorm:"column:original_link_hash;primaryKey" json:"original_link_hash"`
	Forbidden        bool      `gorm:"column:forbidden;not null" json:"forbidden"`
	OriginalLink     string    `gorm:"column:original_link;not null" json:"original_link"`
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName ForbiddenLink's table name
func (*ForbiddenLink) TableName() string {
	return TableNameForbiddenLink
}
