// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCreateLinkLimit = "pikpak_create_link_limit"

// CreateLinkLimit mapped from table <pikpak_create_link_limit>
type CreateLinkLimit struct {
	AutoID          int64     `gorm:"column:auto_id;primaryKey;autoIncrement:true;comment:Auto-increment ID" json:"auto_id"`
	KeepshareUserID string    `gorm:"column:keepshare_user_id;not null;comment:KeepShare user ID" json:"keepshare_user_id"`
	IPLimit         int32     `gorm:"column:ip_limit;not null;comment:Maximum number of allowed IPs" json:"ip_limit"`
	UnitTime        int32     `gorm:"column:unit_time;not null;comment:Time period in seconds" json:"unit_time"`
	Ext             string    `gorm:"column:ext;not null;comment:Extended field for future use" json:"ext"`
	CreatedAt       time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:Record creation time" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:Record update time" json:"updated_at"`
}

// TableName CreateLinkLimit's table name
func (*CreateLinkLimit) TableName() string {
	return TableNameCreateLinkLimit
}
