// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/KeepShareOrg/keepshare/hosts/pikpak/model"
)

func newCreateLinkLimit(db *gorm.DB, opts ...gen.DOOption) createLinkLimit {
	_createLinkLimit := createLinkLimit{}

	_createLinkLimit.createLinkLimitDo.UseDB(db, opts...)
	_createLinkLimit.createLinkLimitDo.UseModel(&model.CreateLinkLimit{})

	tableName := _createLinkLimit.createLinkLimitDo.TableName()
	_createLinkLimit.ALL = field.NewAsterisk(tableName)
	_createLinkLimit.AutoID = field.NewInt64(tableName, "auto_id")
	_createLinkLimit.KeepshareUserID = field.NewString(tableName, "keepshare_user_id")
	_createLinkLimit.IPLimit = field.NewInt32(tableName, "ip_limit")
	_createLinkLimit.UnitTime = field.NewInt32(tableName, "unit_time")
	_createLinkLimit.Ext = field.NewString(tableName, "ext")
	_createLinkLimit.CreatedAt = field.NewTime(tableName, "created_at")
	_createLinkLimit.UpdatedAt = field.NewTime(tableName, "updated_at")

	_createLinkLimit.fillFieldMap()

	return _createLinkLimit
}

type createLinkLimit struct {
	createLinkLimitDo

	ALL             field.Asterisk
	AutoID          field.Int64  // Auto-increment ID
	KeepshareUserID field.String // KeepShare user ID
	IPLimit         field.Int32  // Maximum number of allowed IPs
	UnitTime        field.Int32  // Time period in seconds
	Ext             field.String // Extended field for future use
	CreatedAt       field.Time   // Record creation time
	UpdatedAt       field.Time   // Record update time

	fieldMap map[string]field.Expr
}

func (c createLinkLimit) Table(newTableName string) *createLinkLimit {
	c.createLinkLimitDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c createLinkLimit) As(alias string) *createLinkLimit {
	c.createLinkLimitDo.DO = *(c.createLinkLimitDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *createLinkLimit) updateTableName(table string) *createLinkLimit {
	c.ALL = field.NewAsterisk(table)
	c.AutoID = field.NewInt64(table, "auto_id")
	c.KeepshareUserID = field.NewString(table, "keepshare_user_id")
	c.IPLimit = field.NewInt32(table, "ip_limit")
	c.UnitTime = field.NewInt32(table, "unit_time")
	c.Ext = field.NewString(table, "ext")
	c.CreatedAt = field.NewTime(table, "created_at")
	c.UpdatedAt = field.NewTime(table, "updated_at")

	c.fillFieldMap()

	return c
}

func (c *createLinkLimit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *createLinkLimit) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 7)
	c.fieldMap["auto_id"] = c.AutoID
	c.fieldMap["keepshare_user_id"] = c.KeepshareUserID
	c.fieldMap["ip_limit"] = c.IPLimit
	c.fieldMap["unit_time"] = c.UnitTime
	c.fieldMap["ext"] = c.Ext
	c.fieldMap["created_at"] = c.CreatedAt
	c.fieldMap["updated_at"] = c.UpdatedAt
}

func (c createLinkLimit) clone(db *gorm.DB) createLinkLimit {
	c.createLinkLimitDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c createLinkLimit) replaceDB(db *gorm.DB) createLinkLimit {
	c.createLinkLimitDo.ReplaceDB(db)
	return c
}

type createLinkLimitDo struct{ gen.DO }

type ICreateLinkLimitDo interface {
	gen.SubQuery
	Debug() ICreateLinkLimitDo
	WithContext(ctx context.Context) ICreateLinkLimitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ICreateLinkLimitDo
	WriteDB() ICreateLinkLimitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ICreateLinkLimitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ICreateLinkLimitDo
	Not(conds ...gen.Condition) ICreateLinkLimitDo
	Or(conds ...gen.Condition) ICreateLinkLimitDo
	Select(conds ...field.Expr) ICreateLinkLimitDo
	Where(conds ...gen.Condition) ICreateLinkLimitDo
	Order(conds ...field.Expr) ICreateLinkLimitDo
	Distinct(cols ...field.Expr) ICreateLinkLimitDo
	Omit(cols ...field.Expr) ICreateLinkLimitDo
	Join(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo
	RightJoin(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo
	Group(cols ...field.Expr) ICreateLinkLimitDo
	Having(conds ...gen.Condition) ICreateLinkLimitDo
	Limit(limit int) ICreateLinkLimitDo
	Offset(offset int) ICreateLinkLimitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ICreateLinkLimitDo
	Unscoped() ICreateLinkLimitDo
	Create(values ...*model.CreateLinkLimit) error
	CreateInBatches(values []*model.CreateLinkLimit, batchSize int) error
	Save(values ...*model.CreateLinkLimit) error
	First() (*model.CreateLinkLimit, error)
	Take() (*model.CreateLinkLimit, error)
	Last() (*model.CreateLinkLimit, error)
	Find() ([]*model.CreateLinkLimit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreateLinkLimit, err error)
	FindInBatches(result *[]*model.CreateLinkLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.CreateLinkLimit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ICreateLinkLimitDo
	Assign(attrs ...field.AssignExpr) ICreateLinkLimitDo
	Joins(fields ...field.RelationField) ICreateLinkLimitDo
	Preload(fields ...field.RelationField) ICreateLinkLimitDo
	FirstOrInit() (*model.CreateLinkLimit, error)
	FirstOrCreate() (*model.CreateLinkLimit, error)
	FindByPage(offset int, limit int) (result []*model.CreateLinkLimit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ICreateLinkLimitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (c createLinkLimitDo) Debug() ICreateLinkLimitDo {
	return c.withDO(c.DO.Debug())
}

func (c createLinkLimitDo) WithContext(ctx context.Context) ICreateLinkLimitDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c createLinkLimitDo) ReadDB() ICreateLinkLimitDo {
	return c.Clauses(dbresolver.Read)
}

func (c createLinkLimitDo) WriteDB() ICreateLinkLimitDo {
	return c.Clauses(dbresolver.Write)
}

func (c createLinkLimitDo) Session(config *gorm.Session) ICreateLinkLimitDo {
	return c.withDO(c.DO.Session(config))
}

func (c createLinkLimitDo) Clauses(conds ...clause.Expression) ICreateLinkLimitDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c createLinkLimitDo) Returning(value interface{}, columns ...string) ICreateLinkLimitDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c createLinkLimitDo) Not(conds ...gen.Condition) ICreateLinkLimitDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c createLinkLimitDo) Or(conds ...gen.Condition) ICreateLinkLimitDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c createLinkLimitDo) Select(conds ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c createLinkLimitDo) Where(conds ...gen.Condition) ICreateLinkLimitDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c createLinkLimitDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) ICreateLinkLimitDo {
	return c.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (c createLinkLimitDo) Order(conds ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c createLinkLimitDo) Distinct(cols ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c createLinkLimitDo) Omit(cols ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c createLinkLimitDo) Join(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c createLinkLimitDo) LeftJoin(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c createLinkLimitDo) RightJoin(table schema.Tabler, on ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c createLinkLimitDo) Group(cols ...field.Expr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c createLinkLimitDo) Having(conds ...gen.Condition) ICreateLinkLimitDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c createLinkLimitDo) Limit(limit int) ICreateLinkLimitDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c createLinkLimitDo) Offset(offset int) ICreateLinkLimitDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c createLinkLimitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ICreateLinkLimitDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c createLinkLimitDo) Unscoped() ICreateLinkLimitDo {
	return c.withDO(c.DO.Unscoped())
}

func (c createLinkLimitDo) Create(values ...*model.CreateLinkLimit) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c createLinkLimitDo) CreateInBatches(values []*model.CreateLinkLimit, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c createLinkLimitDo) Save(values ...*model.CreateLinkLimit) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c createLinkLimitDo) First() (*model.CreateLinkLimit, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreateLinkLimit), nil
	}
}

func (c createLinkLimitDo) Take() (*model.CreateLinkLimit, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreateLinkLimit), nil
	}
}

func (c createLinkLimitDo) Last() (*model.CreateLinkLimit, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreateLinkLimit), nil
	}
}

func (c createLinkLimitDo) Find() ([]*model.CreateLinkLimit, error) {
	result, err := c.DO.Find()
	return result.([]*model.CreateLinkLimit), err
}

func (c createLinkLimitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CreateLinkLimit, err error) {
	buf := make([]*model.CreateLinkLimit, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c createLinkLimitDo) FindInBatches(result *[]*model.CreateLinkLimit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c createLinkLimitDo) Attrs(attrs ...field.AssignExpr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c createLinkLimitDo) Assign(attrs ...field.AssignExpr) ICreateLinkLimitDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c createLinkLimitDo) Joins(fields ...field.RelationField) ICreateLinkLimitDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c createLinkLimitDo) Preload(fields ...field.RelationField) ICreateLinkLimitDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c createLinkLimitDo) FirstOrInit() (*model.CreateLinkLimit, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreateLinkLimit), nil
	}
}

func (c createLinkLimitDo) FirstOrCreate() (*model.CreateLinkLimit, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CreateLinkLimit), nil
	}
}

func (c createLinkLimitDo) FindByPage(offset int, limit int) (result []*model.CreateLinkLimit, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c createLinkLimitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c createLinkLimitDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c createLinkLimitDo) Delete(models ...*model.CreateLinkLimit) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *createLinkLimitDo) withDO(do gen.Dao) *createLinkLimitDo {
	c.DO = *do.(*gen.DO)
	return c
}
