// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/KeepShareOrg/keepshare/server/model"
)

func newForbiddenLink(db *gorm.DB, opts ...gen.DOOption) forbiddenLink {
	_forbiddenLink := forbiddenLink{}

	_forbiddenLink.forbiddenLinkDo.UseDB(db, opts...)
	_forbiddenLink.forbiddenLinkDo.UseModel(&model.ForbiddenLink{})

	tableName := _forbiddenLink.forbiddenLinkDo.TableName()
	_forbiddenLink.ALL = field.NewAsterisk(tableName)
	_forbiddenLink.ChannelID = field.NewString(tableName, "channel_id")
	_forbiddenLink.OriginalLinkHash = field.NewString(tableName, "original_link_hash")
	_forbiddenLink.Forbidden = field.NewBool(tableName, "forbidden")
	_forbiddenLink.OriginalLink = field.NewString(tableName, "original_link")
	_forbiddenLink.CreatedAt = field.NewTime(tableName, "created_at")
	_forbiddenLink.UpdatedAt = field.NewTime(tableName, "updated_at")

	_forbiddenLink.fillFieldMap()

	return _forbiddenLink
}

type forbiddenLink struct {
	forbiddenLinkDo

	ALL              field.Asterisk
	ChannelID        field.String
	OriginalLinkHash field.String
	Forbidden        field.Bool
	OriginalLink     field.String
	CreatedAt        field.Time
	UpdatedAt        field.Time

	fieldMap map[string]field.Expr
}

func (f forbiddenLink) Table(newTableName string) *forbiddenLink {
	f.forbiddenLinkDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f forbiddenLink) As(alias string) *forbiddenLink {
	f.forbiddenLinkDo.DO = *(f.forbiddenLinkDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *forbiddenLink) updateTableName(table string) *forbiddenLink {
	f.ALL = field.NewAsterisk(table)
	f.ChannelID = field.NewString(table, "channel_id")
	f.OriginalLinkHash = field.NewString(table, "original_link_hash")
	f.Forbidden = field.NewBool(table, "forbidden")
	f.OriginalLink = field.NewString(table, "original_link")
	f.CreatedAt = field.NewTime(table, "created_at")
	f.UpdatedAt = field.NewTime(table, "updated_at")

	f.fillFieldMap()

	return f
}

func (f *forbiddenLink) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *forbiddenLink) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 6)
	f.fieldMap["channel_id"] = f.ChannelID
	f.fieldMap["original_link_hash"] = f.OriginalLinkHash
	f.fieldMap["forbidden"] = f.Forbidden
	f.fieldMap["original_link"] = f.OriginalLink
	f.fieldMap["created_at"] = f.CreatedAt
	f.fieldMap["updated_at"] = f.UpdatedAt
}

func (f forbiddenLink) clone(db *gorm.DB) forbiddenLink {
	f.forbiddenLinkDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f forbiddenLink) replaceDB(db *gorm.DB) forbiddenLink {
	f.forbiddenLinkDo.ReplaceDB(db)
	return f
}

type forbiddenLinkDo struct{ gen.DO }

type IForbiddenLinkDo interface {
	gen.SubQuery
	Debug() IForbiddenLinkDo
	WithContext(ctx context.Context) IForbiddenLinkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IForbiddenLinkDo
	WriteDB() IForbiddenLinkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IForbiddenLinkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IForbiddenLinkDo
	Not(conds ...gen.Condition) IForbiddenLinkDo
	Or(conds ...gen.Condition) IForbiddenLinkDo
	Select(conds ...field.Expr) IForbiddenLinkDo
	Where(conds ...gen.Condition) IForbiddenLinkDo
	Order(conds ...field.Expr) IForbiddenLinkDo
	Distinct(cols ...field.Expr) IForbiddenLinkDo
	Omit(cols ...field.Expr) IForbiddenLinkDo
	Join(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo
	Group(cols ...field.Expr) IForbiddenLinkDo
	Having(conds ...gen.Condition) IForbiddenLinkDo
	Limit(limit int) IForbiddenLinkDo
	Offset(offset int) IForbiddenLinkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IForbiddenLinkDo
	Unscoped() IForbiddenLinkDo
	Create(values ...*model.ForbiddenLink) error
	CreateInBatches(values []*model.ForbiddenLink, batchSize int) error
	Save(values ...*model.ForbiddenLink) error
	First() (*model.ForbiddenLink, error)
	Take() (*model.ForbiddenLink, error)
	Last() (*model.ForbiddenLink, error)
	Find() ([]*model.ForbiddenLink, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ForbiddenLink, err error)
	FindInBatches(result *[]*model.ForbiddenLink, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.ForbiddenLink) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IForbiddenLinkDo
	Assign(attrs ...field.AssignExpr) IForbiddenLinkDo
	Joins(fields ...field.RelationField) IForbiddenLinkDo
	Preload(fields ...field.RelationField) IForbiddenLinkDo
	FirstOrInit() (*model.ForbiddenLink, error)
	FirstOrCreate() (*model.ForbiddenLink, error)
	FindByPage(offset int, limit int) (result []*model.ForbiddenLink, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IForbiddenLinkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (f forbiddenLinkDo) Debug() IForbiddenLinkDo {
	return f.withDO(f.DO.Debug())
}

func (f forbiddenLinkDo) WithContext(ctx context.Context) IForbiddenLinkDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f forbiddenLinkDo) ReadDB() IForbiddenLinkDo {
	return f.Clauses(dbresolver.Read)
}

func (f forbiddenLinkDo) WriteDB() IForbiddenLinkDo {
	return f.Clauses(dbresolver.Write)
}

func (f forbiddenLinkDo) Session(config *gorm.Session) IForbiddenLinkDo {
	return f.withDO(f.DO.Session(config))
}

func (f forbiddenLinkDo) Clauses(conds ...clause.Expression) IForbiddenLinkDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f forbiddenLinkDo) Returning(value interface{}, columns ...string) IForbiddenLinkDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f forbiddenLinkDo) Not(conds ...gen.Condition) IForbiddenLinkDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f forbiddenLinkDo) Or(conds ...gen.Condition) IForbiddenLinkDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f forbiddenLinkDo) Select(conds ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f forbiddenLinkDo) Where(conds ...gen.Condition) IForbiddenLinkDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f forbiddenLinkDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) IForbiddenLinkDo {
	return f.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (f forbiddenLinkDo) Order(conds ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f forbiddenLinkDo) Distinct(cols ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f forbiddenLinkDo) Omit(cols ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f forbiddenLinkDo) Join(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f forbiddenLinkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f forbiddenLinkDo) RightJoin(table schema.Tabler, on ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f forbiddenLinkDo) Group(cols ...field.Expr) IForbiddenLinkDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f forbiddenLinkDo) Having(conds ...gen.Condition) IForbiddenLinkDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f forbiddenLinkDo) Limit(limit int) IForbiddenLinkDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f forbiddenLinkDo) Offset(offset int) IForbiddenLinkDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f forbiddenLinkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IForbiddenLinkDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f forbiddenLinkDo) Unscoped() IForbiddenLinkDo {
	return f.withDO(f.DO.Unscoped())
}

func (f forbiddenLinkDo) Create(values ...*model.ForbiddenLink) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f forbiddenLinkDo) CreateInBatches(values []*model.ForbiddenLink, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f forbiddenLinkDo) Save(values ...*model.ForbiddenLink) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f forbiddenLinkDo) First() (*model.ForbiddenLink, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ForbiddenLink), nil
	}
}

func (f forbiddenLinkDo) Take() (*model.ForbiddenLink, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ForbiddenLink), nil
	}
}

func (f forbiddenLinkDo) Last() (*model.ForbiddenLink, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ForbiddenLink), nil
	}
}

func (f forbiddenLinkDo) Find() ([]*model.ForbiddenLink, error) {
	result, err := f.DO.Find()
	return result.([]*model.ForbiddenLink), err
}

func (f forbiddenLinkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ForbiddenLink, err error) {
	buf := make([]*model.ForbiddenLink, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f forbiddenLinkDo) FindInBatches(result *[]*model.ForbiddenLink, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f forbiddenLinkDo) Attrs(attrs ...field.AssignExpr) IForbiddenLinkDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f forbiddenLinkDo) Assign(attrs ...field.AssignExpr) IForbiddenLinkDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f forbiddenLinkDo) Joins(fields ...field.RelationField) IForbiddenLinkDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f forbiddenLinkDo) Preload(fields ...field.RelationField) IForbiddenLinkDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f forbiddenLinkDo) FirstOrInit() (*model.ForbiddenLink, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ForbiddenLink), nil
	}
}

func (f forbiddenLinkDo) FirstOrCreate() (*model.ForbiddenLink, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ForbiddenLink), nil
	}
}

func (f forbiddenLinkDo) FindByPage(offset int, limit int) (result []*model.ForbiddenLink, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f forbiddenLinkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f forbiddenLinkDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f forbiddenLinkDo) Delete(models ...*model.ForbiddenLink) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *forbiddenLinkDo) withDO(do gen.Dao) *forbiddenLinkDo {
	f.DO = *do.(*gen.DO)
	return f
}
